### Add product
POST http://localhost:3000/api/product-add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFiMTk4MzdkYzIzM2VjZDBmMWY3MTQiLCJpYXQiOjE3NDY2MDY0NzMsImV4cCI6MTc0OTE5ODQ3M30.WVWuwxNBeKVElieGdvxQ0To8mcs0C1Im2YnoZZJRmWM

{
    "title": "Test from rest",
    "description":
      "Test fromr rest",
    "artist": "Test from Nutty",
    "price": 123456,
    "sellerName": "Nutty",
    "image":
      "dragon-tempura-sprint2/public/productPicture/Portrait-Painting-Modern-Art-2.jpg",
    "dimensions": "142cm x 102cm x 4cm",
    "material": "No matter",
    "yearCreated": 1850,
    "tags": ["Portrait", "Historical", "Classic"]
}

### Get product
GET http://localhost:3000/api/product-get
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjNjA4N2FjYjI3NDRkMDZjOGM5Y2MiLCJpYXQiOjE3NDY2OTM2OTcsImV4cCI6MTc0OTI4NTY5N30.ADUqtR9QhIVk5_GEOt0DedSLK42FpUp_EErZLwcaaFo

### Get product by userId
GET http://localhost:3000/api/product-get/681b19837dc233ecd0f1f714
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE1Y2ZkYTc4Y2RjMjRlZDkzMDI1N2EiLCJpYXQiOjE3NDYyNjM5MjgsImV4cCI6MTc0ODg1NTkyOH0.X_Pdirz-ZNOxbqkK6HrXSpVJ3WgRJJx1Tp-SN93DgUc

### Edit by put product
PUT http://localhost:3000/api/product-put/681da8b47118d603ecd8d3f9
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFhZDY5YzU3ODhmZTUwOTNmMTEzMzkiLCJpYXQiOjE3NDY3NzIwNTMsImV4cCI6MTc0OTM2NDA1M30.7eifdlfc6fhtAlbVDGx57R_c3RZNrFbX35XH1a7NRCo

{
    "title": "Test from rest by Nutty",
    "description":
      "Test fromr rest by Nutty",
    "artist": "Test from Nutty",
    "price": 1234566666666666666666666666,
    "sellerName": "Nutty",
    "image":
      "dragon-tempura-sprint2/public/productPicture/Portrait-Painting-Modern-Art-2.jpg",
    "dimensions": "142cm x 102cm x 4cm",
    "material": "No matter",
    "yearCreated": 1850,
    "tags": ["Portrait", "Historical", "Classic"]
}

### Delete product by productId
DELETE http://localhost:3000/api/product-delete/6815d50ba54d919e0adc03f2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE1Y2ZkYTc4Y2RjMjRlZDkzMDI1N2EiLCJpYXQiOjE3NDYyNjM5MjgsImV4cCI6MTc0ODg1NTkyOH0.X_Pdirz-ZNOxbqkK6HrXSpVJ3WgRJJx1Tp-SN93DgUc

###
GET http://localhost:3000/api/my-products
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjNjA4N2FjYjI3NDRkMDZjOGM5Y2MiLCJpYXQiOjE3NDY2OTM2OTcsImV4cCI6MTc0OTI4NTY5N30.ADUqtR9QhIVk5_GEOt0DedSLK42FpUp_EErZLwcaaFo

###
GET http://localhost:3000/api/product-get/681da8b47118d603ecd8d3f9
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjNjA4N2FjYjI3NDRkMDZjOGM5Y2MiLCJpYXQiOjE3NDY2OTM2OTcsImV4cCI6MTc0OTI4NTY5N30.ADUqtR9QhIVk5_GEOt0DedSLK42FpUp_EErZLwcaaFo
