### Register
POST http://localhost:3000/api/users-register
Content-Type: application/json

{
    "firstName": "Ling",
    "lastName": "Dragon",
    "email": "dragonLing@example.com",
    "password": "123456789zZ",
    "phone": "0123456789"
}

### Login
POST http://localhost:3000/api/users-login
Content-Type: application/json

{
    "email": "dragonLing@example.com",
    "password": "123456789zZ"
}

### Logout user
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFiMTk4MzdkYzIzM2VjZDBmMWY3MTQiLCJpYXQiOjE3NDY2MzUwNTIsImV4cCI6MTc0OTIyNzA1Mn0.Bu9avjVZLAXG5UvrAfLCkbsLJP7aPMy24IjhhncGyNA


### Reset password
PATCH http://localhost:3000/api/users-resetpassword
Content-Type: application/json

{
    "email": "dragonLing@example.com",
    "password": "Reset23456789zZ"
}

### Get user
GET http://localhost:3000/api/users
### Get user By userId
GET http://localhost:3000/api/users/6814356e36166409f6c60e18