### Register
POST http://localhost:3000/api/users-register
Content-Type: application/json

{
    "firstName": "Ling",
    "lastName": "Dragon",
    "email": "dragonLing@example.com",
    "password": "123456789zZ",
    "phone": "0123456789"
}

### Login
POST http://localhost:3000/api/users-login
Content-Type: application/json

{
    "email": "dragonLing@example.com",
    "password": "123456789zZ"
}

### Reset password
PATCH http://localhost:3000/api/users-resetpassword
Content-Type: application/json

{
    "email": "dragonLing@example.com",
    "password": "Reset23456789zZ"
}

### Get user
GET http://localhost:3000/api/users
### Get user By userId
GET http://localhost:3000/api/users/6814356e36166409f6c60e18